name: food-fraud
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - snakemake-minimal=8.*
  - biopython=1.84
  - pandas=2.2.*
  - pyyaml=6.*
  - matplotlib=3.9.*
  - fastp=0.24.*
  - vsearch=2.29.*
  - blast=2.16.*
  - minimap2=2.28
  - seqkit=2.9.*
  - nanoq=0.10.*
  - chopper=0.9.*
  - samtools=1.21
